#creation of the list
prog_lan=['c','python','java','html','c++','css',]
print(prog_lan)
print(type(prog_lan))
print("acessing the list elements using positive index:")
print("-----------------------------------")
print(prog_lan[0])
print(prog_lan[1])
print(prog_lan[2])
print(prog_lan[3])
print(prog_lan[4])
print(prog_lan[5])
print("_________________________")
print("acessing negative elements:")
print("-------------------")
print(prog_lan[-6])
print(prog_lan[-5])
print(prog_lan[-4])
print(prog_lan[-3])
print(prog_lan[-2])
print(prog_lan[-1])
