cartoons=['tom&jerry','krishna aur balram','hiedi','chota bheem','dora','shinchan','doremon']
print(cartoons)
print("after appending:")
cartoons.append('oggy&cockroaches')
print(cartoons)
print("after inseting elements:")
cartoons.insert(2,'roll number 21')
print(cartoons)
print("after popping the elements:")
cartoons.pop()
print(cartoons)
cartoons.pop(4)
print(cartoons)
cartoons.remove('dora')
print(cartoons)
print(cartoons.index('tom&jerry'))
print("after reversing the list:")
cartoons.reverse()
print(cartoons)