Emp_Name=input("enter the name of the employee:")
Desg=input("enter the designation of the employee:")
Sal=input("enter Ethe salary of the employee:")
Special_Allowances=input("enter the special allowances of the employee:")
Bonus=input("enter the bonus of the employee:")
print("employee report card:")
print("--------------------")
print("employee name:",Emp_Name)
print("Designation:",Desg)
print("Salary:",Sal)
print("special allowances are:",Special_Allowances)
print("Bonus",Bonus)
print("----------------")
gross_sal=(Sal+Special_Allowances)
print("gross_sal is",gross_sal)
gross_annual=(gross_sal*12+Bonus)
print("gross_annual :",gross_annual)