amount=int(input("enter the amount:"))
intrest=int(input("enter the intrest:"))
time=int(input("enter the time"))
print("details:")
print("-------")
print("amount is",amount)
print("intrest is",intrest)
print("time taken",time)
simpleintrest=((amount*intrest*time)/100)
print("simpkle intrest is:",simpleintrest)