tuple=(15,20)
print(tuple)
print(type(tuple))
print("_----------------")
tuple1='py','cpp','java'
print(tuple1)
print("--------------------------")
tuple=('pyhton','java','c++','java','dart','flutter','go-lang','react js','angular')
print("acessing positive index value:")
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print(tuple[6])
print(tuple[7])